### ISSUE TITLE
c_test_easy_task2.json and c_test_hard_task2.json can't find

### ISSUE THREAD

**Issue by liubo12** [nonstopfor/Sticker-Selection#1]
I fail to run this baseline because I can't find the files c_test_easy_task2.json and c_test_hard_task2.json. I download all the file accornding to the README.md in the file folder data. So where is the data?

**Comment by nonstopfor** [comment]
There is a test folder in that url. And the test data is in the README.md in that folder.
https://drive.google.com/drive/folders/1HXAQBJeaMnxb7oj-sfyqtkbX_NEjY5BZ
