### ISSUE TITLE
AttributeError: 'CLIPModel' object has no attribute 'preprocess'

### ISSUE THREAD

**Issue by wxj630** [nonstopfor/Sticker-Selection#2]
File "main.py", line 690, in prepare_imgs
    self.img_process = self.img_clip._first_module().preprocess

AttributeError: 'CLIPModel' object has no attribute 'preprocess'

**Comment by nonstopfor** [comment]
Please check whether the version of sentence_transformers is 2.0.0

**Comment by wxj630** [comment]
if I use sentence-transformers  2.0.0，another error occured:

File "main.py", line 66, in __init__
    self.img_clip = SentenceTransformer('clip-ViT-B-32')
File "/home/xxxxxx/miniconda3/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 90, in __init__
    modules = self._load_sbert_model(model_path)
  File "/home/xxxxx/miniconda3/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 822, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "/home/xxxxxx/miniconda3/lib/python3.8/site-packages/sentence_transformers/models/CLIPModel.py", line 90, in load
    model_path = os.path.join(input_path, config['model_name'])
KeyError: 'model_name'

**Comment by nonstopfor** [comment]
Did you run `pip install -r requirements.txt` ?

**Comment by wxj630** [comment]
yes, all packages in requirements.txt are satisfied

**Comment by wxj630** [comment]
I comment out “import clip” because there is  not clip package in requirements.txt

**Comment by wxj630** [comment]
may you send me these file 
1、"sentence_transformers/models/CLIPModel.py" 
2、clip pretrained model dir and config.json , is it the same as https://huggingface.co/sentence-transformers/clip-ViT-B-32 ?

in you environment through email for debugging ?

**Comment by wxj630** [comment]
I found that  there were something update in  https://huggingface.co/sentence-transformers/clip-ViT-B-32 last 6 months ，can you check the differences in pretrained model between huggingface.co and you local file ?

**Comment by liubo12** [comment]
Facing the same error, and update sentence_transformers==2.1.0 doesnt work as well

**Comment by nonstopfor** [comment]
It seems that sentence_tranformers has changed its checkpoint so the old version doesn't work now according to [https://github.com/UKPLab/sentence-transformers/issues/1241](https://github.com/UKPLab/sentence-transformers/issues/1241). Maybe it is better to use the lastest version of sentence_tranformers and change the code a little bit (change the code to get the image embedding).

**Comment by nonstopfor** [comment]
I find a quicker way to solve this. Use sentence_transformers==2.0.0 and download the files in [https://huggingface.co/sentence-transformers/clip-ViT-B-32/tree/3fa6f52ec56d58d65a46c4139ed508fe92b5f5e1](https://huggingface.co/sentence-transformers/clip-ViT-B-32/tree/3fa6f52ec56d58d65a46c4139ed508fe92b5f5e1) to use the old checkpoint.

**Comment by wxj630** [comment]
> I find a quicker way to solve this. Use sentence_transformers==2.0.0 and download the files in https://huggingface.co/sentence-transformers/clip-ViT-B-32/tree/3fa6f52ec56d58d65a46c4139ed508fe92b5f5e1 to use the old checkpoint.

it works, thank you very much.

**Comment by wxj630** [comment]
After i finish training the model and generate prediction files, If I want to see the test acc, is it the only way sending [feizhengcong@ict.ac.cn](mailto:feizhengcong@ict.ac.cn)  the prediction results?

**Comment by nonstopfor** [comment]
Yes. And please ask zekangli97@gmail.com now.

**Comment by Gary-code** [comment]
> Yes. And please ask [zekangli97@gmail.com](mailto:zekangli97@gmail.com) now.

The dataset owner doesn't reply to my email. Could you provide this test data result. Looking forward to your reply.
